### ISSUE TITLE
platformio config for the Arduino sketch

### ISSUE THREAD

**Issue by bertrik** [shakso/EnergyMonitor#1]
I'm a big fan of platformio and I'd like to help you make it easier for people to compile the Arduino part.

Basically platformio support means you add a platform.ini file. It specifies what microcontroller you use, what libraries (and their specific versions!). This way you can build the arduino code from the command line, outside of the Arduino IDE. You don't need to have instructions on what 'extra' toolchains to install, or specific instructions for specific versions of libraries. It's all specified in a single platformio.ini

Would you be willing to accept a patch adding a platformio.ini configuration file?

I've been working on very similar ideas. I'm using a RGB ring light, driven by an ESP microcontroller. It polls a simple HTTP REST API that provides information about electricity price (per hour), electricity generation data (per 15 minutes), natural gas price (per day). See
https://revspace.nl/PowerLight

**Comment by shakso** [comment]
Nice project - I'm happy to accept a patch for platformio config
